<?php

error_reporting(E_ALL);

$data = array(
    array(
        'sku' => 'test1234',
        '_store' => '',
        '_attribute_set' => 'Components-Set',
        '_type' => 'simple',
        '_category' => 'Motorrad/Auspuffanlagen',
        '_category' => 'Motorrad/Auspuffanlagen/Akrapovic',
        '_root_category' => 'Components',
        '_product_websites' => 'base',
        'buildyear' => '1980',
        'color' => 'white',
        'country_of_manufacture' => '',
        'created_at' => '29.05.2015 - 09:48',
        'custom_design' => '',
        'custom_design_from' => '',
        'custom_design_to' => '',
        'custom_layout_update' => '',
        'delivery_time' => 'Kann nicht versendet werden',
        'description' => 'Der wohl beste Programmierer der Welt',
        'gallery' => '',
        'gift_message_available' => '',
        'has_options' => '0',
        'image' => '/image1.jpg',
        'image_label' => 'Name Bild 1',
        'image' => '/image2.jpg',
        'image_label' => 'Name Bild 2',		
        'manufacturer' => 'Mama',
        'media_gallery' => '',
        'meta_autogenerate' => 'ja',
        'meta_description' => '',
        'meta_keyword' => '',
        'meta_title' => '',
        'minimal_price' => '',
        'model' => 'Deutscher',
        'msrp' => '',
        'msrp_display_actual_price_type' => 'Konfiguration verwenden',
        'msrp_enabled' => 'Konfiguration verwenden',
        'name' => 'Magento Entwickler',
        'news_from_date' => '',
        'news_to_date' => '',
        'options_container' => 'Artikelinformationsspalte',
        'page_layout' => '',
        'required_options' => '0',
        'revocation_product_type' => '',
        'short_description' => 'Kurz und Knackig',
        'small_image' => '/image1.jpg',
        'small_image_label' => 'Hauptbild',
        'special_from_date' => '',
        'special_price' => '',
        'special_to_date' => '',
        'status' => '1',
        'tax_class_id' => '1',
        'thumbnail' => '/image1.jpg',
        'thumbnail_label' => 'Hauptbild',
        'url_key' => '',
        'url_path' => '',
        'visibility' => '4',
        'weight' => '0',
        'qty' => '10',
        'min_qty' => '1',
        'use_config_min_qty' => '1',
        'is_qty_decimal' => '0',
        'backorders' => '0',
        'use_config_backorders' => '1',
        'min_sale_qty' => '10.000',
        'use_config_min_sale_qty' => '1',
        'max_sale_qty' => '0.0000',
        'use_config_max_sale_qty' => '1',
        'is_in_stock' => '1',
        'notify_stock_qty' => '',
        'use_config_notify_stock_qty' => '1',
        'manage_stock' => '0',
        'use_config_manage_stock' => '1',
        'stock_status_changed_auto' => '0',
        'use_config_qty_increments' => '1',
        'qty_increments' => '0.0000',
        'use_config_enable_qty_inc' => '1',
        'enable_qty_increments' => '0',
        'is_decimal_divided' => '0',
        '_links_related_sku' => '',
        '_links_related_position' => '',
        '_links_crosssell_sku' => '',
        '_links_crosssell_position' => '',
        '_links_upsell_sku' => '',
        '_links_upsell_position' => '',
        '_associated_sku' => '',
        '_associated_default_qty' => '',
        '_associated_position' => '',
        '_tier_price_website' => '',
        '_tier_price_customer_group' => '',
        '_tier_price_qty' => '',
        '_tier_price_price' => '',
        '_group_price_website' => '',
        '_group_price_customer_group' => '',
        '_group_price_price' => '',
        '_media_attribute_id' => '88',
        '_media_image' => '/image1.jpg',
        '_media_lable' => 'Bild 1',
        '_media_position' => '1',
        '_media_is_disabled' => '0',
        '_media_attribute_id' => '88',
        '_media_image' => '/image2.jpg',
        '_media_lable' => 'Bild 2',
        '_media_position' => '2',
        '_media_is_disabled' => '0',
    ),
    // add more products here
);

/** @var $import AvS_FastSimpleImport_Model_Import */
$import = Mage::getModel('fastsimpleimport/import');
try {
    $import->processProductImport($data);
} catch (Exception $e) {
    print_r($import->getErrorMessages());
}
?>